version: '3.8'
services:
  dalos:
    container_name: dalos_app
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - ./:/app
 